name               = "grm"
main               = "src/index.ts"
compatibility_date = "2024-07-25"

# For local development, use `wrangler dev` to start a local server
[dev]
ip             = "0.0.0.0"
port           = 8787
local_protocol = "http"

[vars]
VERSION = "2.1.0"
SERVICE_NAME = "grm"
DOMAINS = ["batchnorm.dpdns.org"]
FORBID_HTML = true

# Development delpoyment
[env.development]
name = "grm"

[env.development.vars]
VERSION = "2.1.0"
SERVICE_NAME = "grm"
DOMAINS = ["batchnorm.dpdns.org"]
FORBID_HTML = true

# Production deployment
[env.production]
name = "grm"
minify = true

[env.production.vars]
VERSION = "2.1.0"
SERVICE_NAME = "grm"
DOMAINS = ["batchnorm.dpdns.org"]
FORBID_HTML = true

